name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "71.0"
      - name: Download geckodriver
        uses: browser-actions/setup-geckodriver@latest
        with:
          geckodriver-version: "0.26.0"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6.5"
          bundler-cache: true
      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            bundle install
            bundle exec rake spec
